@url = https://localhost:5001

###
GET {{url}}

### Create order.
# @name create_order
POST {{url}}/orders
Content-Type: application/json

{
  "buyerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "address": {
    "city": "New York",
    "street": "20 W 34th St",
    "province": "New York",
    "country": "United States",
    "zipCode": "NY 10001"
  },
  "items": [
    {
      "name": "Ice creams",
      "quantity": 2,
      "unitPrice": 1.80
    },
    {
      "name": "Coffee",
      "quantity": 1,
      "unitPrice": 3.00
    },
    {
      "name": "Apple pie",
      "quantity": 1,
      "unitPrice": 5.49
    }
  ]
}

@orderId = {{create_order.response.headers.Location}}

### Get order by ID.
GET {{url}}/orders/{{orderId}}

### Get list of orders.
GET {{url}}/orders
